version: "3"

services:
    app:
        build: .
        ports:
            - 3000:3000
        environment:
            PORT: 3000
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_PASSWORD: password
        depends_on:
            - redis

    redis:
        image: redis
        ports:
            - 6379:6379
